<?php


namespace Ennq\MedsTheme\Seeders\PagesSeeders;


use Anomaly\PagesModule\Page\Contract\PageRepositoryInterface;
use Anomaly\PagesModule\Type\Contract\TypeRepositoryInterface;
use Anomaly\Streams\Platform\Database\Seeder\Seeder;
use Ennq\MedsTheme\Seeders\BaseSeeders\BaseSeeder;
use Ennq\MedsTheme\Seeders\Menu\MenuSeeder;

class Seeder31 extends BaseSeeder
{

    public static function getTitle(): string
    {
        return 'Календарь профилактических исследований для разных возрастных групп';
    }

    public static function getSlug(): string
    {
        return '/cdiaglcalendar';
    }

    public static function getParentSlug(): ?string
    {
        return MenuSeeder::SLUG_CDIAGL;
    }

    protected function getContent(): string
    {
        return
'
<div>
    <p style="padding-bottom: 7px">
        В каждом возрастном периоде следует обращать внимание на определенные показатели своего организма, которые мы назвали зонами мониторинга. Одни зоны мониторинга являются общими для любого возраста, другие - специфичны и нуждаются в исследовании только в определенные годы жизни.
    </p>
    <p style="padding-bottom: 7px">
        <span style="color: red;">Красным цветом</span> отмечены исследования проводимые на <span style="color: red; text-decoration: underline;">платной основе</span>.
    </p>
    <p style="padding-bottom: 7px">
        <span style="color: green;">Зеленым цветом</span> отмечены исследования <span style="color: green; text-decoration: underline;">НЕ проводимые</span> на базе КДЛ Красногорской ГБ №2.
    </p>
    <p style="padding-bottom: 7px; text-align: center">
        <h4>Календарь профилактических исследований для разных возрастных групп (+ подгруппы)</h4>
    </p>
    <p style="padding-bottom: 7px">
        <table style="width: 100%" id="meds-table" class="table table-striped table-bordered dt-responsive nowrap">
            <thead>
                <tr>
                    <td>ВОЗРАСТ<br>АНАЛИЗЫ</td>
                    <td>18</td>
                    <td>19</td>
                    <td>20</td>
                    <td>21</td>
                    <td>22</td>
                    <td>23</td>
                    <td>24</td>
                    <td>25</td>
                    <td>26</td>
                    <td>27</td>
                    <td>28</td>
                    <td>29</td>
                    <td>30</td>
                    <td>31</td>
                    <td>32</td>
                    <td>33</td>
                    <td>34</td>
                    <td>35</td>
                    <td>36</td>
                    <td>37</td>
                    <td>38</td>
                    <td>39</td>
                    <td>40</td>
                    <td>41-50</td>
                    <td>51-60</td>
                    <td>61-70</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Клинический анализ крови</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                </tr>
                <tr>
                    <td>Общий анализ мочи</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                </tr>
                <tr>
                    <td>Глюкоза/<span style="color: red;">Гликированный гемоглобин</span></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                </tr>
                <tr>
                    <td>Холестерин и <span style="color: red;">липидный профиль</span></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                </tr>
                <tr>
                    <td><span style="color: red;">Гормоны щитовидной железы (ТТГ, Т3, Т4, АТ-ТГ, АТ-ТПО) + УЗИ</span></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                </tr>
                <tr>
                    <td><span style="color: red;">Обследование на инфекции, передаваемые половым путем (ИППП)</span></td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                </tr>
                <tr>
                    <td><span style="color: red;">Сердечно-сосудистая система (протромбин + МНО, фибриноген, антистрептолизин, ревматоидный фактор, «С»-реактивный белок</span></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </p>
    <p style="padding-bottom: 7px; text-align: center">
        <h4>Дополнительно для женщин</h4>
    </p>
    <p style="padding-bottom: 7px">
        <table style="width: 100%" id="meds-table" class="table table-striped table-bordered dt-responsive nowrap">
            <thead>
                <tr>
                    <td></td>
                    <td>18</td>
                    <td>19</td>
                    <td>20</td>
                    <td>21</td>
                    <td>22</td>
                    <td>23</td>
                    <td>24</td>
                    <td>25</td>
                    <td>26</td>
                    <td>27</td>
                    <td>28</td>
                    <td>29</td>
                    <td>30</td>
                    <td>31</td>
                    <td>32</td>
                    <td>33</td>
                    <td>34</td>
                    <td>35</td>
                    <td>36</td>
                    <td>37</td>
                    <td>38</td>
                    <td>39</td>
                    <td>40</td>
                    <td>41-50</td>
                    <td>51-60</td>
                    <td>61-70</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Гинекологический мазок на флору</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                </tr>
                <tr>
                    <td>Цитологическое исследование шейки матки + УЗИ матки и придатков</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                </tr>
                <tr>
                    <td>Глюкоза/<span style="color: green;">Онкомаркер молочной железы СА 15-3</span> и <span style="color: red;">УЗИ молочной железы</span></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                </tr>
                <tr>
                    <td><span style="color: green;">Онкомаркер яичников СА-125, альфафетопротеин, РЭА, СА 19-9, СА 72-4, Cyfra 21-1, Белок S-100, SCC, NSE</span></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                </tr>
                <tr>
                    <td><span style="color: red;">Эндокринная система (пролактин, ЛГ, ФСГ,  Эстрадиол, Прогестерон, Тестостерон)</span></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </p>
    <p style="padding-bottom: 7px; text-align: center">
        <h4>Дополнительно для мужчин</h4>
    </p>
    <p style="padding-bottom: 7px">
        <table style="width: 100%" id="meds-table" class="table table-striped table-bordered dt-responsive nowrap">
            <thead>
                <tr>
                    <td></td>
                    <td>18</td>
                    <td>19</td>
                    <td>20</td>
                    <td>21</td>
                    <td>22</td>
                    <td>23</td>
                    <td>24</td>
                    <td>25</td>
                    <td>26</td>
                    <td>27</td>
                    <td>28</td>
                    <td>29</td>
                    <td>30</td>
                    <td>31</td>
                    <td>32</td>
                    <td>33</td>
                    <td>34</td>
                    <td>35</td>
                    <td>36</td>
                    <td>37</td>
                    <td>38</td>
                    <td>39</td>
                    <td>40</td>
                    <td>41-50</td>
                    <td>51-60</td>
                    <td>61-70</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><span style="color: green;">Урологический мазок на флору</span></td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                </tr>
                <tr>
                    <td><span style="color: red;">Онкомаркер предстательной железы ПСА общ.</span> + <span style="color: green;">РЭА, SCC, Белок S100, AFP, SCC, CA 15-3, CA 19-9, CA 72-4, Cyfra 21-1, NSE</span></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                    <td>+</td>
                </tr>
                <tr>
                    <td><span style="color: red;">Эндокринная система (пролактин, ЛГ, ФСГ, эстрадиол, тестостерон)</span></td>
                    <td>+</td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>+</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        <p style="padding-bottom: 7px; text-align: center">
            <h4>Календарь профилактических исследований у детей</h4>
        </p>
        <p style="padding-bottom: 7px">
            <table style="width: 100%" id="meds-table" class="table table-striped table-bordered dt-responsive nowrap">
                <thead>
                    <tr>
                        <td>ВОЗРАСТ<br>АНАЛИЗЫ</td>
                        <td>3м</td>
                        <td>6м</td>
                        <td>9м</td>
                        <td>1г</td>
                        <td>1,5г</td>
                        <td>2г</td>
                        <td>3г</td>
                        <td>4г</td>
                        <td>5л</td>
                        <td>6л</td>
                        <td>7л</td>
                        <td>8л</td>
                        <td>9л</td>
                        <td>10л</td>
                        <td>11л</td>
                        <td>12л</td>
                        <td>13л</td>
                        <td>14л</td>
                        <td>15л</td>
                        <td>16л</td>
                        <td>17л</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><span style="color: red;">Общее состояние организма и функциональная работа внутренних органов (Холестерин, Общий белок, Креатинин, Мочевина, Кальций общий, Фосфор, Железосывороточное, Калий, Натрий)</span></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                    </tr>
                    <tr>
                        <td>Клинический анализ крови, общий анализ мочи</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                    </tr>
                    <tr>
                        <td>Глюкоза</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                    </tr>
                    <tr>
                        <td><span style="color: red;">Пищеварительная система (АЛТ, АСТ, щелочная фосфатаза, Альфа-амилаза, билирубин общ. и пр., ЛДГ, копрограмма)</span></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                    </tr>
                    <tr>
                        <td><span style="color: red;">Эндокриннаясистема (Гликозилированный гемоглобин, ТТГ, Т3,Т4, анти-ТГ, анти-ТПО)</span></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                    </tr>
                    <tr>
                        <td>Исследование на энтеробиоз, исследование кала и яйца гельминтов</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                    </tr>
                    <tr>
                        <td><span style="color: red;">
                            Исследование кала на простейщие, крови на Ат к Ascaris IgG (аскарида)
                            Ат к Giardia lamblia (лямблии) суммарные
                            Ат к описторхам (Opisthorchis) IgG
                            Ат к эхинококку (Echinococcus) IgG
                            Ат к токсокаре (Toxocara canis) IgG
                            Ат к трихинелле (Trichinella) IgG
                        </span></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                    </tr>
                    <tr>
                        <td><span style="color: red;">Контроль над прививками</span></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><span style="color: red;">Инфекции, передающиеся половым путем (ИППП)</span></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                        <td>+</td>
                    </tr>
                </tbody>
            </table>
        </p>
    </p>
    <p style="padding-bottom: 7px">
        Каждый из нас в любом возрасте должен заботиться о своем здоровье. При этом необходимо помнить, что забота о здоровье – это не только лечение, но  прежде всего профилактика и поддержание здорового состояния организма. Календарь исследований, разработанный на основании требований и рекомендаций МЗ РФ и Всемирной организации здравоохранения, поможет Вам узнать, какие общие и дополнительные лабораторные обследования необходимо проходить ежегодно  как женщине, так и мужчине, в соответствии с возрастом.
    </p>
</div>
';
    }
}
