version: '2'
services:
    redis:
        image: redis:latest
        container_name: meds-redis
    p_web_server:
        build:
            context: .
            dockerfile: nginx/nginx.docker
        container_name: p_web_server
        volumes:
            - ../:/var/www
            - ./nginx/ssl:/etc/nginx/ssl
        ports:
            - "9090:80"
        links:
            - p_php_fpm
    p_php_fpm:
        build:
            context: .
            dockerfile: php-fpm/php-fpm.docker
        container_name: p_php_fpm
        volumes:
            - ../:/var/www
            - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        links:
            - db
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=db"
    db:
        image: mysql:5.7
        volumes:
            - ../storage/docker/mysql:/var/lib/mysql
        container_name: db
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=admin"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=meds"
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        links:
            - db
        ports:
            - "8080:80"
        volumes:
            - /sessions
# UNIX_SOCKET=/var/run/mysqld/mysqld.sock
